name: autoupdate-tag

on:
    push:
        branches:
            - 'main'
    pull_request:
        types: [ labeled, opened, synchronized ]
        branches:
            - 'main'

env:
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
    merge-branch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Branch name
              run: echo branch ${BRANCH_NAME}

            - name: Merge main -> PR branch
              if: contains(github.event.pull_request.labels.*.name, 'autoupdate') || github.ref == 'refs/head/main'
              uses: devmasx/merge-branch@master
              with:
                type: now
                from_branch: main
                target_branch: ${GITHUB_REF##*/}
