name: autoupdate-tag

on:
    push:
        branches:
            - 'main'
    pull_request:
        types: [ labeled, opened ]
        branches:
            - 'main'

jobs:
    merge-branch:
        if: contains(github.event.pull_request.labels.*.name, '<label_name>') || steps.branch-name.outputs.is_default == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Merge main -> PR branch
              uses: devmasx/merge-branch@master
              with:
                type: now
                from_branch: main
                target_branch: ${GITHUB_REF##*/}
